### PR TITLE
Revoke force

### PR DESCRIPTION
**Pull request by kodieGlosser**
Provide an option for a force flag when revoking a certificate.

### CODE REVIEW

**Comment by kodieGlosser** [comment]
@ecrist Hello Eric. I'm tagging you because I see you committed a bunch on this repo. It looks like your travis checks have been failing for some time. 

I see errors like `^-- SC2154: out_key_pass is referenced but not assigned.`
I'm not sure if you know this, I do it in my own bash script, but you can ignore these errors to get travis to pass successfully. Right above the line in complains about you can add:
`# shellcheck disable=SC2154`

**Comment by kodieGlosser** [comment]
PR to fix travis https://github.com/OpenVPN/easy-rsa/pull/192

**Comment by ecrist** [comment]
Can you explain to me what force is meant to do and the work flow you've identified that necessitates the feature?

**Comment by kodieGlosser** [comment]
Right, so when we revoke a certificate currently, we need to interact with the shell to confirm that, yes we want to revoke the certificate. It makes it hard to automate this because for me I need to install extra dependencies to reply "yes" to the revoke of the certificate. With this feature it will allow us to just pass in `-f` or `--force` to allow the certificate to be revoke without any interaction with the terminal. 

So the workflow would stay the same for the existing functionality
`./easyrsa revoke <cert>` will still do everything it expects

`./easyrsa revoke <badparam> <cert>` will fail out because there was 2 parameters and the first was not a force option. 

`./easyrsa revoke -f <cert>` will revoke the cert without any input from the user.

**Comment by ecrist** [comment]
Is this not already handled by the --batch option?  If not, I think that would be a better way to handle this.

**Comment by TinCanTech** [comment]
This is the function of `--batch`.

No reply in 4 years, closed.

**Pull request closed without merging**
