### PR TITLE
easyrsa: add show-ca command to display the ca certificate

### PR DESCRIPTION
**Pull request by solidgoldbomb**
The new 'show-ca [full]' command dumps out the CA certificate in a similar manner to the way the 'show-cert' command does.

Just let me know if you would like any changes.

### CODE REVIEW

**Comment by solidgoldbomb** [comment]
Any interest in this feature?  If not, I can close this and maintain it on a local branch.

**Comment by TinCanTech** [comment]
I like it and have cloned it

**Comment by ecrist** [comment]
Is this better than a simple openssl command?  

`openssl x509 -noout -text -in ca.crt`

**Comment by solidgoldbomb** [comment]
Technically, it's not really doing any more than you could already do directly with openssl.  But that's true of many of the things you can already do with easy-rsa.  It's more about helping just enough that the user can perform some introspection on their setup without remembering the openssl command line parameters.

The show-cert command fills out the list of helper commands:
 * The show-cert command dumps a signed cert without directly using openssl + params + filepath
 * The show-req does the same for requests
 * The (new) show-ca command does the same for the ca certificate

I believe this patch ends up running:
```
openssl x509 -in path/ca.crt -noout -text -nameopt multiline -certopt no_pubkey,no_sigdump
```
unless you say 'full' in which case it runs:
```
openssl x509 -in path/ca.crt -noout -text -nameopt multiline
```

**Comment by solidgoldbomb** [comment]
Are you still looking for feedback on this one?  I've locally tested a rebase onto the latest master and it still works properly.  Would you like me to submit a new patch for this feature?

**Comment by TinCanTech** [comment]
I believe this complements the `show-cert` command and **is useful**.
It looks to be fairly maintenance free.
I vote this be merged.

**Comment by solidgoldbomb** [comment]
I rebased this branch to master.  My changes rebased cleanly.  It appears as though the travis-ci test-runner failed during setup due to an unrelated error.  Is this an expected error on master?
```
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install shellcheck
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 libc6-dev : Breaks: binutils (< 2.26) but 2.24-5ubuntu14.2 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
apt-get.diagnostics
apt-get install failed
$ cat ${TRAVIS_HOME}/apt-get-update.log
Get:1 http://ftp.us.debian.org/debian unstable InRelease [237 kB]

[...]

W: There is no public key available for the following key IDs:
7638D0442B90D010
E: Invalid message from method gpgv:  NO_PUBKEY 04EE7237B7D453EC
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install shellcheck" failed and exited with 100 during .
```

**Comment by ecrist** [comment]
I've merged this in 391948f with a minor correction in 272ee0e for branch v3.0.6.

**Comment by solidgoldbomb** [comment]
Thanks for merging.

**Pull request closed without merging**
