### PR TITLE
upgrade pki: fix paths

### PR DESCRIPTION
**Pull request by vazhnov**
Closes: #474.

### CODE REVIEW

**Comment by TinCanTech** [comment]
Regarding your [patch](https://github.com/OpenVPN/easy-rsa/pull/475), sorry, Nack. Changing `$EASYRSA` for Duvian is too intrusive.

Your wiki update is ok.

**Comment by vazhnov** [comment]
@TinCanTech, I understand. Thank you for a help!

**Comment by TinCanTech** [comment]
@vazhnov I was not asking you to close this PR, I only left my personal feedback.

**Comment by TinCanTech** [comment]
@vazhnov I cannot take the change to `ChangeLog` because we do not know if this _fixes_ the problem. But the PR is still ok otherwise.

**Pull request closed without merging**
