### PR TITLE
busybox: Upload working Windows executable as 7zip

### PR DESCRIPTION
**Pull request by TinCanTech**
busybox.exe: BusyBox v1.37.0.git (2023-02-07 21:41:11 GMT)

easyrsa-windows-conf: make configuration file to build busybox.

README.txt: Further details.

Signed-off-by: Richard T Bonhomme <tincantech@protonmail.com>

### CODE REVIEW

**Comment by TinCanTech** [comment]
Source: https://github.com/rmyorston/busybox-w32

Built on Fedora.

`make` config file for building busybox for use with EasyRSA included.

**Comment by rmyorston** [comment]
You can save 30K (uncompressed) if you omit the embedded icons.

Yes, "pretty is a feature", but in this case it's probably not worth >10% the size of the binary.
```diff
--- ./configs/easyrsa_defconfig.orig	2023-02-08 09:24:50.000000000 +0000
+++ ./configs/easyrsa_defconfig	2023-02-08 09:29:14.000000000 +0000
@@ -47,10 +47,10 @@ CONFIG_FEATURE_PRNG_SHELL=y
 # CONFIG_FEATURE_PRNG_ISAAC is not set
 CONFIG_FEATURE_RESOURCES=y
 CONFIG_FEATURE_VERSIONINFO=y
-CONFIG_FEATURE_ICON=y
+# CONFIG_FEATURE_ICON is not set
 # CONFIG_FEATURE_ICON_ATERM is not set
 # CONFIG_FEATURE_ICON_STERM is not set
-CONFIG_FEATURE_ICON_ALL=y
+# CONFIG_FEATURE_ICON_ALL is not set
 # CONFIG_FEATURE_EURO is not set
 CONFIG_SKIP_ANSI_EMULATION_DEFAULT=2
 CONFIG_FEATURE_IMPROVED_COLOUR_MAPPING=y
```

**Comment by TinCanTech** [comment]
@rmyorston Thank you for the tip!

I have been experimenting with `menuconfig`, I'll try this too.

**Comment by TinCanTech** [comment]
Force push: v4, remove embedded icons, `[` and `test`.

Full unit-test completed locally.

**Comment by TinCanTech** [comment]
Closing this, possibly move to a feature branch.

**Comment by TinCanTech** [comment]
Re-opening as a possible follow-up to: #1075

**Comment by rmyorston** [comment]
Thanks for the heads up.

>I would like to credit your work.

That would be appreciated. A mention in `README-Windows.txt` would be sufficient.

I suggest you also publicise the BusyBox configuration file you used and the version or commit of the source. This will in useful in case any bugs are identified.

**Pull request closed without merging**
