### PR TITLE
add x509-type client/server

### PR DESCRIPTION
**Pull request by tschulze**

### CODE REVIEW

**Comment by tschulze** [comment]
add x509-type client/server

**Comment by alonbl** [comment]
better to add a type option to build-full instead of having a parameter for each

**Comment by ecrist** [comment]
What is the use case for this change?  Where a certificate is used as both a client and a server?

**Comment by alonbl** [comment]
> 
> 
> What is the use case for this change? Where a certificate is used as both a client and a server?

Kafka, Couchbase, microservices and many more cases.

**Comment by ecrist** [comment]
Merged into v3.0.6 in bebd71e

**Pull request closed without merging**
