### PR TITLE
fixed renew filename confusion

### PR DESCRIPTION
**Pull request by patchhoernchen**
fixed missing quotes leading to filename inconsistency in renew subcommand.

### CODE REVIEW

**Comment by ecrist** [comment]
Straight forward. I'll push this is the next couple days.

**Comment by TinCanTech** [comment]
Have to wonder why `$1` is not the same as `"$1"` ..

**Comment by trasherdk** [comment]
Space character in path requires vars to be quoted.

Also. vars ought to be ${VAR} to be sure.

**Comment by TinCanTech** [comment]
But `$1` does not contain any `$PATH` ..

**Comment by ecrist** [comment]
$1 can still contain spaces. Despite what is in path. Adding quotes wouldn't break anything regardless.

**Comment by TinCanTech** [comment]
> $1 can still contain spaces. Despite what is **in path**

> Space character **in path** requires vars to be quoted

I do not believe you are focused on the issue being presented to you.

**Comment by trasherdk** [comment]
Okay. I'll bite. What is the *issue being presented* ?

And how did the global `$PATH` get involved ?

**Comment by patchhoernchen** [comment]
Hi,
to clarify the reason for this pull request here is a description of my observed behaviour:

If a file basename conatains spaces, only its first, not-by-space delimited part will be used as filename. This behaviour is inconsisten with other file basename using commands and will produce unexpected filenames.

It could probably lead to unwanted overwriting of other files, but i have not investigated that.
I observed this behaviour yesterday on versions 1.0.6 and 1.0.8.

**Comment by TinCanTech** [comment]
> If a file basename conatains spaces

This is the point I was getting at. I doubt very much if Easy-RSA will work properly with spaces in base_name.

**Comment by patchhoernchen** [comment]
> > If a file basename conatains spaces
> 
> This is the point I was getting at. I doubt very much if Easy-RSA will work properly with spaces in base_name.

I don't see any reason for that doubt, but maybe I'm not into it enough. On the other hand, if it intentionally does not support whitespaces I would expect a check/santisation on the basename.

From my experience I can say that creation of client-certificates with spaces in basename is working fine. With this fix renewal worked also well.

**Comment by TinCanTech** [comment]
I apologies for my unnecessary noise here.

**Pull request merged**
