### PR TITLE
Insert functional code: install_data_to_pki()

### PR DESCRIPTION
**Pull request by Prouflon**
Adding to #508 

I propose a shorter version of install_data_to_pki()

From my commit:
The previous patch made it difficult to potentially add additional
configuration directories from other package managers.
This patch introduces check_global_config(), which allows for holistic
scanning of a directory with one call.
It is integrated into the existing install_data_to_pki()

### CODE REVIEW

**Comment by Prouflon** [comment]
_Meta_: I don't know how to propose changes to other Pull requests other than leaving a review. I don't mean to spam this repo with Pull requests.

**Comment by TinCanTech** [comment]
> I don't mean to spam this repo with Pull requests

Your help and feedback is of **tremendous value**, I encourage you to use this repo.

**Comment by TinCanTech** [comment]
This Patch-set is here for discussion an destruction.

The code you don't like above is simply a first draft, every thing is there to see in simple but long winded code. The task is to agree to the changes and them make good changes.

I have a second draft, which is much more compact.

**Review by TinCanTech — COMMENTED** [review]
It looks like we are on the same page `:-)`

FTR: I don't think either #508 or #509 are going to be merged, this is discussion at this time.

**Comment by Prouflon** [comment]
I am trying to wrap my head around all the other changes .

What is `$EASYRSA_PKI_SAFE_CONF` and what should it contain?
https://github.com/OpenVPN/easy-rsa/blob/79d5b20fff6a6fe41517899714ceab40e03ad159/easyrsa3/easyrsa#L727-L729
It is not set with `'easyrsa_openssl() makesafeconf'`, that much I am sure of.
Was that an oversight?
https://github.com/OpenVPN/easy-rsa/blob/79d5b20fff6a6fe41517899714ceab40e03ad159/easyrsa3/easyrsa#L2042-L2043

**Comment by TinCanTech** [comment]
> What is `$EASYRSA_PKI_SAFE_CONF` and what should it contain?

It should be the file-name of the safe SSL conf in the PKI folder, which is the same as `EASYRSA_SAFE_CONF` and is an over-sight by me.  Thank you very much for taking the time to spot this!

**Comment by Prouflon** [comment]
Improved by #510

**Pull request closed without merging**
