### PR TITLE
Multiple fix for build-dist.sh

### PR DESCRIPTION
**Pull request by luizluca**
* Added --no-windows, --no-unix and no --no-compress to skip some
build steps.
* Use cp in a Linux and FreeBSD compatible way
* Set 'sed -i' backup extension (Linux and FreeBSD compatible)
  (Linux regression from f0204c160b3cbdc041a91f2861febab24b7f5f76)
* Fix zip location to match tar (fixing also --bin-dest for win32)
* Align (y/n) with question in confirm

Signed-off-by: Luiz Angelo Daros de Luca <luizluca@gmail.com>

### CODE REVIEW

**Comment by luizluca** [comment]
Just rebasing on v3.0.6

**Comment by luizluca** [comment]
Done!

**Comment by ecrist** [comment]
Thanks!  In the future, please use options -sS so you GPG sign your commit and also add the "Signed off by:" line to the commit.

**Comment by luizluca** [comment]
Sure. Nothing that a forced rebase (git rebase -S -f HEAD~2) cannot fix

**Pull request merged**
