### PR TITLE
use easyrsa3/easyrsa in build-dist.sh

### PR DESCRIPTION
**Pull request by luizluca**
Signed-off-by: Luiz Angelo Daros de Luca <luizluca@gmail.com>

### CODE REVIEW

**Comment by ecrist** [comment]
This correction is wrong. The distribution root removes the extra easyrsa3 path.

**Comment by luizluca** [comment]
@ecrist, the code clearly copies easyrsa3/ dir into $DIST_ROOT/unix/$PV/. There is no way to have a easyrsa file at $DIST_ROOT/unix/$PV/easyrsa.

If sed is write, the code before it is broken.

BTW, EasyRSA-nix-3.0.5.tgz looks like it was hand-made. There is two easyrsa scripts, one suffixed with "-e" that matches the source code one. It seems to be a left over file.

To put this discussion in context, I'm doing some easy-rsa maintenance for OpenWrt. The "release" version isn't suitable for packing as it is too complex to apply a patch from git into a directory tree that does not match the source. That's why I'm using the source code tar.gz. easy-rsa does not have a Makefile for "make install" or an "./install.sh" script but the "build-dist.sh" that builds tar.gz for win32 and UNIX. However, "build-dist.sh" is simply not working.

**Comment by ecrist** [comment]
Luiz,

I do not hand-make the tarball files, so not sure why you think that.  Additionally, this script works correctly in my use of it to package the files, including replacing the ~~~ with the correct version string.

-----
Eric F Crist
Sr Integration Engineer
Author: Troubleshooting OpenVPN
Co-Author: Mastering OpenVPN

**Comment by luizluca** [comment]
@ecrist ,

It looks like hand-made because released build-dist.sh doesn't generate the released tar ball.

```
$ wget -nv https://github.com/OpenVPN/easy-rsa/archive/v3.0.5.tar.gz
2018-10-01 19:18:11 URL:https://codeload.github.com/OpenVPN/easy-rsa/tar.gz/v3.0.5 [638366] -> "v3.0.5.tar.gz" [1]

$ tar -xzf v3.0.5.tar.gz 

$ cd easy-rsa-3.0.5/

$ ./build/build-dist.sh --version=3.0.5
sed: can't read dist-staging/unix/EasyRSA-3.0.5/easyrsa: No such file or directory
/usr/bin/python: No module named markdown
/usr/bin/python: No module named markdown
/usr/bin/python: No module named markdown
/usr/bin/python: No module named markdown
/usr/bin/python: No module named markdown
/usr/bin/python: No module named markdown
/usr/bin/python: No module named markdown
/usr/bin/python: No module named markdown
unix2dos: converting file dist-staging/windows/EasyRSA-3.0.5/README-Windows.txt to DOS format...
unix2dos: converting file dist-staging/windows/EasyRSA-3.0.5/EasyRSA-Start.bat to DOS format...
'./distro/windows/bin' -> 'dist-staging/windows/EasyRSA-3.0.5/bin'
'./distro/windows/bin/awk.exe' -> 'dist-staging/windows/EasyRSA-3.0.5/bin/awk.exe'
'./distro/windows/bin/cat.exe' -> 'dist-staging/windows/EasyRSA-3.0.5/bin/cat.exe'
'./distro/windows/bin/cp.exe' -> 'dist-staging/windows/EasyRSA-3.0.5/bin/cp.exe'
'./distro/windows/bin/diff.exe' -> 'dist-staging/windows/EasyRSA-3.0.5/bin/diff.exe'
'./distro/windows/bin/easyrsa-shell-init.sh' -> 'dist-staging/windows/EasyRSA-3.0.5/bin/easyrsa-shell-init.sh'
'./distro/windows/bin/grep.exe' -> 'dist-staging/windows/EasyRSA-3.0.5/bin/grep.exe'
'./distro/windows/bin/ls.exe' -> 'dist-staging/windows/EasyRSA-3.0.5/bin/ls.exe'
'./distro/windows/bin/md5sum.exe' -> 'dist-staging/windows/EasyRSA-3.0.5/bin/md5sum.exe'
'./distro/windows/bin/mkdir.exe' -> 'dist-staging/windows/EasyRSA-3.0.5/bin/mkdir.exe'
'./distro/windows/bin/mktemp.exe' -> 'dist-staging/windows/EasyRSA-3.0.5/bin/mktemp.exe'
'./distro/windows/bin/mv.exe' -> 'dist-staging/windows/EasyRSA-3.0.5/bin/mv.exe'
'./distro/windows/bin/printf.exe' -> 'dist-staging/windows/EasyRSA-3.0.5/bin/printf.exe'
'./distro/windows/bin/rm.exe' -> 'dist-staging/windows/EasyRSA-3.0.5/bin/rm.exe'
'./distro/windows/bin/sed.exe' -> 'dist-staging/windows/EasyRSA-3.0.5/bin/sed.exe'
'./distro/windows/bin/sh.exe' -> 'dist-staging/windows/EasyRSA-3.0.5/bin/sh.exe'
'./distro/windows/bin/which.exe' -> 'dist-staging/windows/EasyRSA-3.0.5/bin/which.exe'
build-dist NOTE: tarball created at: ./EasyRSA-3.0.5.tgz
build-dist NOTE: zip file created at: ./EasyRSA-3.0.5.zip

$ tar -tvf dist-staging/unix/EasyRSA-3.0.5.tgz 
drwxr-xr-x luizluca/domain users 0 2018-10-01 19:18 EasyRSA-3.0.5/
drwxr-xr-x luizluca/domain users 0 2018-09-15 01:18 EasyRSA-3.0.5/Licensing/
-rw-r--r-- luizluca/domain users 18093 2018-09-15 01:18 EasyRSA-3.0.5/Licensing/gpl-2.0.txt
-rw-r--r-- luizluca/domain users  1036 2018-09-15 01:18 EasyRSA-3.0.5/Licensing/mktemp.txt
-rw-r--r-- luizluca/domain users  1970 2018-09-15 01:18 EasyRSA-3.0.5/README.md
drwxr-xr-x luizluca/domain users     0 2018-09-15 01:18 EasyRSA-3.0.5/easyrsa3/
-rw-r--r-- luizluca/domain users  8459 2018-09-15 01:18 EasyRSA-3.0.5/easyrsa3/vars.example
-rw-r--r-- luizluca/domain users  4566 2018-09-15 01:18 EasyRSA-3.0.5/easyrsa3/openssl-easyrsa.cnf
drwxr-xr-x luizluca/domain users     0 2018-09-15 01:18 EasyRSA-3.0.5/easyrsa3/x509-types/
-rw-r--r-- luizluca/domain users   192 2018-09-15 01:18 EasyRSA-3.0.5/easyrsa3/x509-types/client
-rw-r--r-- luizluca/domain users   193 2018-09-15 01:18 EasyRSA-3.0.5/easyrsa3/x509-types/code-signing
-rw-r--r-- luizluca/domain users   208 2018-09-15 01:18 EasyRSA-3.0.5/easyrsa3/x509-types/server
-rw-r--r-- luizluca/domain users   300 2018-09-15 01:18 EasyRSA-3.0.5/easyrsa3/x509-types/COMMON
-rw-r--r-- luizluca/domain users   426 2018-09-15 01:18 EasyRSA-3.0.5/easyrsa3/x509-types/ca
-rwxr-xr-x luizluca/domain users 38856 2018-09-15 01:18 EasyRSA-3.0.5/easyrsa3/easyrsa
-rw-r--r-- luizluca/domain users  3335 2018-09-15 01:18 EasyRSA-3.0.5/README.quickstart.md
-rw-r--r-- luizluca/domain users  3231 2018-09-15 01:18 EasyRSA-3.0.5/ChangeLog
-rw-r--r-- luizluca/domain users  1305 2018-09-15 01:18 EasyRSA-3.0.5/COPYING.md
drwxr-xr-x luizluca/domain users     0 2018-10-01 19:18 EasyRSA-3.0.5/doc/
-rw-r--r-- luizluca/domain users  9562 2018-10-01 19:18 EasyRSA-3.0.5/doc/EasyRSA-Readme.md
-rw-r--r-- luizluca/domain users  4923 2018-10-01 19:18 EasyRSA-3.0.5/doc/Intro-To-PKI.md
-rw-r--r-- luizluca/domain users  5891 2018-10-01 19:18 EasyRSA-3.0.5/doc/Hacking.md
-rw-r--r-- luizluca/domain users  5389 2018-10-01 19:18 EasyRSA-3.0.5/doc/EasyRSA-Advanced.md
-rw-r--r-- luizluca/domain users  2496 2018-10-01 19:18 EasyRSA-3.0.5/doc/EasyRSA-Upgrade-Notes.md
```

The first output line of ./build/build-dist.sh shows that sed cannot find the file.

The presence of a easyrsa.e in released tarball looks like the sed command used was something like "sed -ie ...". '-i' has an optional argument for a backup file and it cannot be merged with '-e'. sed command in released build-dist.sh is correct.

released build-dist.sh does not copy easyrsa3/easyrsa to the place sed will look and also where files are in released tarball.

Either a different non-published build-dist.sh was used or it was hand-made. And, probably, it has the 'sed -ie ...' bug.

**Comment by ecrist** [comment]
You cannot run the build-dist.sh script from the release tarball.  You can only run it from a checkout from git.

-----
Eric F Crist
Sr Integration Engineer
Author: Troubleshooting OpenVPN
Co-Author: Mastering OpenVPN

**Comment by ecrist** [comment]
OK, so I realized that you are using the source tarball from the release, not the actual release tarball.  Understand that I build the tarballs on FreeBSD, without the majority of that GNU crud.  In particular, sed behaves differently on FreeBSD.  The presence of the easyrsa-e file is actually an error due to sed differences.  The in-place edit on BSD sed is done with a -I, whereas in-place edit in GNU sed is done with -i.  I will add some detection in the build script to accommodate these differences.

This works just fine for me:

ecrist@terrance:~/easy-rsa-3.0.5-> build/build-dist.sh --version=3.0.5
./distro/windows/bin -> dist-staging/windows/EasyRSA-3.0.5/bin
./distro/windows/bin/awk.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/awk.exe
./distro/windows/bin/cat.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/cat.exe
./distro/windows/bin/cp.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/cp.exe
./distro/windows/bin/diff.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/diff.exe
./distro/windows/bin/easyrsa-shell-init.sh -> dist-staging/windows/EasyRSA-3.0.5/bin/easyrsa-shell-init.sh
./distro/windows/bin/grep.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/grep.exe
./distro/windows/bin/ls.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/ls.exe
./distro/windows/bin/md5sum.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/md5sum.exe
./distro/windows/bin/mkdir.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/mkdir.exe
./distro/windows/bin/mktemp.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/mktemp.exe
./distro/windows/bin/mv.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/mv.exe
./distro/windows/bin/printf.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/printf.exe
./distro/windows/bin/rm.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/rm.exe
./distro/windows/bin/sed.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/sed.exe
./distro/windows/bin/sh.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/sh.exe
./distro/windows/bin/which.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/which.exe
build-dist NOTE: tarball created at: ./EasyRSA-3.0.5.tgz
build-dist NOTE: zip file created at: ./EasyRSA-3.0.5.zip


Here is a much longer version via sh -x.

ecrist@terrance:~/easy-rsa-3.0.5-> sh -x build/build-dist.sh --version=3.0.5
+ VERSION=git-development
+ PRODUCT=EasyRSA
+ DIST_ROOT=dist-staging
+ SRC_ROOT=.
+ BIN_DEST=.
+ [ -n --version=3.0.5 ]
+ cmd=--version
+ val=3.0.5
+ [ --version=3.0.5 = --version ]
+ [ -z 3.0.5 ]
+ VERSION=3.0.5
+ shift
+ [ -n '' ]
+ main
+ PV=EasyRSA-3.0.5
+ dist_clean
+ [ -e dist-staging ]
+ confirm 'Remove existing DIST_ROOT at: '\''dist-staging'\'' ?' ''
+ [ '' ]
+ echo 'Remove existing DIST_ROOT at: '\''dist-staging'\'' ?'
Remove existing DIST_ROOT at: 'dist-staging' ?
+ printf ' y/n: '
 y/n: + read r
y
+ [ y = y ]
+ rm -rf dist-staging
+ mkdir -p dist-staging
+ stage_unix
+ mkdir -p dist-staging/unix/EasyRSA-3.0.5
+ src_files='easyrsa3/ Licensing/ COPYING.md ChangeLog README.md README.quickstart.md'
+ cp -a ./easyrsa3/ dist-staging/unix/EasyRSA-3.0.5
+ cp -a ./Licensing/ dist-staging/unix/EasyRSA-3.0.5
+ cp -a ./COPYING.md dist-staging/unix/EasyRSA-3.0.5
+ cp -a ./ChangeLog dist-staging/unix/EasyRSA-3.0.5
+ cp -a ./README.md dist-staging/unix/EasyRSA-3.0.5
+ cp -a ./README.quickstart.md dist-staging/unix/EasyRSA-3.0.5
+ cp -R ./doc dist-staging/unix/EasyRSA-3.0.5/
+ sed -i -e 's/~~~/3.0.5/' dist-staging/unix/EasyRSA-3.0.5/easyrsa
+ rm -rf dist-staging/unix/EasyRSA-3.0.5/doc/TODO
+ stage_win
+ mkdir -p dist-staging/windows/EasyRSA-3.0.5
+ mkdir -p dist-staging/windows/EasyRSA-3.0.5/doc
+ basename ./doc/EasyRSA-Advanced.md .md
+ fname=EasyRSA-Advanced
+ sed -i -e 's/~~~/3.0.5/' ././doc/EasyRSA-Advanced.md
+ python -m markdown ./doc/EasyRSA-Advanced.md
+ basename ./doc/EasyRSA-Readme.md .md
+ fname=EasyRSA-Readme
+ sed -i -e 's/~~~/3.0.5/' ././doc/EasyRSA-Readme.md
+ python -m markdown ./doc/EasyRSA-Readme.md
+ basename ./doc/EasyRSA-Upgrade-Notes.md .md
+ fname=EasyRSA-Upgrade-Notes
+ sed -i -e 's/~~~/3.0.5/' ././doc/EasyRSA-Upgrade-Notes.md
+ python -m markdown ./doc/EasyRSA-Upgrade-Notes.md
+ basename ./doc/Hacking.md .md
+ fname=Hacking
+ sed -i -e 's/~~~/3.0.5/' ././doc/Hacking.md
+ python -m markdown ./doc/Hacking.md
+ basename ./doc/Intro-To-PKI.md .md
+ fname=Intro-To-PKI
+ sed -i -e 's/~~~/3.0.5/' ././doc/Intro-To-PKI.md
+ python -m markdown ./doc/Intro-To-PKI.md
+ python -m markdown ./README.md
+ python -m markdown ./README.quickstart.md
+ python -m markdown ./COPYING.md
+ src_files='easyrsa3/ ChangeLog COPYING.md'
+ cp -a ./easyrsa3/ dist-staging/windows/EasyRSA-3.0.5
+ cp -a ./ChangeLog dist-staging/windows/EasyRSA-3.0.5
+ cp -a ./COPYING.md dist-staging/windows/EasyRSA-3.0.5
+ src_files='Licensing distro/windows/Licensing'
+ cp -R ./Licensing dist-staging/windows/EasyRSA-3.0.5
+ cp -R ./distro/windows/Licensing dist-staging/windows/EasyRSA-3.0.5
+ src_files='README-Windows.txt EasyRSA-Start.bat'
+ cp -a ./distro/windows/README-Windows.txt dist-staging/windows/EasyRSA-3.0.5
+ unix2dos dist-staging/windows/EasyRSA-3.0.5/README-Windows.txt
+ cp -a ./distro/windows/EasyRSA-Start.bat dist-staging/windows/EasyRSA-3.0.5
+ unix2dos dist-staging/windows/EasyRSA-3.0.5/EasyRSA-Start.bat
+ cp -v -R ./distro/windows/bin dist-staging/windows/EasyRSA-3.0.5/
./distro/windows/bin -> dist-staging/windows/EasyRSA-3.0.5/bin
./distro/windows/bin/awk.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/awk.exe
./distro/windows/bin/cat.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/cat.exe
./distro/windows/bin/cp.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/cp.exe
./distro/windows/bin/diff.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/diff.exe
./distro/windows/bin/easyrsa-shell-init.sh -> dist-staging/windows/EasyRSA-3.0.5/bin/easyrsa-shell-init.sh
./distro/windows/bin/grep.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/grep.exe
./distro/windows/bin/ls.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/ls.exe
./distro/windows/bin/md5sum.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/md5sum.exe
./distro/windows/bin/mkdir.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/mkdir.exe
./distro/windows/bin/mktemp.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/mktemp.exe
./distro/windows/bin/mv.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/mv.exe
./distro/windows/bin/printf.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/printf.exe
./distro/windows/bin/rm.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/rm.exe
./distro/windows/bin/sed.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/sed.exe
./distro/windows/bin/sh.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/sh.exe
./distro/windows/bin/which.exe -> dist-staging/windows/EasyRSA-3.0.5/bin/which.exe
+ rm -rf dist-staging/windows/EasyRSA-3.0.5/doc/TODO
+ make_tar
+ cd dist-staging/unix/
+ tar -czf ./EasyRSA-3.0.5.tgz EasyRSA-3.0.5
+ note 'tarball created at: ./EasyRSA-3.0.5.tgz'
+ echo 'build-dist NOTE: tarball created at: ./EasyRSA-3.0.5.tgz'
build-dist NOTE: tarball created at: ./EasyRSA-3.0.5.tgz
+ make_zip
+ cd dist-staging/windows/
+ zip -qr ../.././EasyRSA-3.0.5.zip EasyRSA-3.0.5
+ note 'zip file created at: ./EasyRSA-3.0.5.zip'
+ echo 'build-dist NOTE: zip file created at: ./EasyRSA-3.0.5.zip'
build-dist NOTE: zip file created at: ./EasyRSA-3.0.5.zip
-----
Eric F Crist
Sr Integration Engineer
Author: Troubleshooting OpenVPN
Co-Author: Mastering OpenVPN

**Comment by luizluca** [comment]
FreeBSD:

```
$ mkdir a
$ touch a/b
$ mkdir c
$ cp -a a/ c
$ ls a
b
$ ls c
b
```

Linux:

```
$ mkdir a
$ touch a/b
$ mkdir c
$ cp -a a/ c
$ ls a
b
$ ls c
a
```

That behavior for 'cp -a', copying dir contents instead of the directory itself is new for me. Linux does not work like that.

I recommend to use something like:

```
$ cp -a a/. c
```

I though Linux would be the main test env as most easy-rsa users do use it. Travis would really help here.

**Comment by ecrist** [comment]
Travis would help.  I will not agree that Linux should be my acid test, however.

-----
Eric F Crist
Sr Integration Engineer
Author: Troubleshooting OpenVPN
Co-Author: Mastering OpenVPN

**Pull request closed without merging**
