### PR TITLE
Add initial simple debian packaging

### PR DESCRIPTION
**Pull request by ChristianTacke**
(my previous pull request got borked while I was trying to rename the branch to be a feature branch.)

Hi, we're going to use easyrsa3 in our company and we require debian/ubuntu packaging to be able to use it. So here is our packaging. I hope it is useful to other people.

Let me know, what needs to be done to get this merged upstream?
Note: We will be available to maintain this. So this is not a maintainance nightmare (things getting added and nobody care for them).

### CODE REVIEW

**Comment by ChristianTacke** [comment]
I have rebased this to the current master to allow easier reviewing/merging.

I would appreciate some feedback on this.
* Is there interest on having maintained debian packaging in the main repository? (As I said: I will be maintaining this for the time being, as my company needs it.)
* If so: What is needed to get it merged?
* If not: Please explain why?

Thanks.

**Comment by ecrist** [comment]
We will look into this over the weekend.  I don't know of any reason you couldn't maintain a debian repo package, regardless what we think, though.

-----
Eric F Crist

**Comment by ChristianTacke** [comment]
Thanks.

Yes, I can maintain it as I do now, obviously. It just might be useful for other people to have one place to find everything (source and packaging).

**Comment by ecrist** [comment]
@ChristianTacke is this still something you'd like committed?  I can do so in v3.0.6.

**Comment by ChristianTacke** [comment]
No, you can just close it.

Debian has packaging for 3.x in testing, which should be usable for all cases.

**Pull request closed without merging**
