### PR TITLE
--show-cert-revokation

### PR DESCRIPTION
**Pull request by z-eos**
- option --show-cert-revokation is added
- CA+CRL (used by FreeRADIUS) generation added

### CODE REVIEW

**Comment by TinCanTech** [comment]
I don't know what you expect this to be:
```
crl="$EASYRSA_PKI/ca+crl.pem"
```

It looks like `bash` ..

**Comment by z-eos** [comment]
it is not bash, it is file name, it is CA and CRL in one file
(it is expected (I don't know why) by FreeRADIUS for example)

**Comment by TinCanTech** [comment]
Please **give** an example of the file-name that you expect.

**Comment by trasherdk** [comment]
While it's a valid filename, on Linux at least, it probably violates every standard imaginable.

**Comment by z-eos** [comment]
to be honest, I'm not sure which "every standard" you mean (yes, a "plus" character is not in [POSIX 3.282 Portable Filename Character Set](https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/), but it is acceptable)

file notation is not important at all, it can be whatever you consider acceptable

the main idea was to have an option to see a revocation state of the cert

**Comment by TinCanTech** [comment]
The file "CA+CRL.pem" is not created by `easyrsa`.

**Comment by z-eos** [comment]
yes, it is created by PR code, but can you be more specific?
If you are against file name with "plus" char, then say what are you agree with?
Is name `ca-crl.pem` OK?

**Comment by TinCanTech** [comment]
It is not the name.

It is that this change will only work for you not `easyrsa.

**Comment by z-eos** [comment]
> It is that this change will only work for you, not easyrsa.

which namely? PR has 2 options

1. the main option: `--show-cert-revocation` 
2. the "auxiliary" creation of combo .pem file CA+CRL 

so, what we're speaking about,pls?

**Comment by TinCanTech** [comment]
Allow me to demonstrate:
```
$ ./easyrsa show-cert-revocation tct.66.c.fed

Easy-RSA error:

Missing expected CRL file: /home/tct/easy-rsa/r66/easyrsa3/pki/ca+crl.pem
```
I conclude that you have not tested this outside of your own environment.

**Comment by TinCanTech** [comment]
https://github.com/OpenVPN/easy-rsa/pull/353/commits/ab6e548cdd2ba0c92383f343ae5f8a5eccf0d455 breaks your own setup.

**Comment by z-eos** [comment]
ok, thanks, I'm closing PR

**Comment by TinCanTech** [comment]
**Note**: The check-Pass above would **fail**, if the unit-test ran your code.

**Comment by TinCanTech** [comment]
@z-eos This idea is ok, but the code is not good.

I will try to write a unit-test for you to check a PR against. I'll update you here if I can do it.

**Comment by TinCanTech** [comment]
Linking: #549 #557 

#557 provides `show-revoke`, which lists the following data:
```
Notice
------
* Showing certificates which are revoked:

R | Serial: 01F9E933F0BB10102F0911A97E6D8D05 | Revoked: Tue 17 May 15:22:47 BST 2022 | Reason: None given | CN: tct.66.c.w7e
```
@z-eos does that satisfy your requirement ?

**Comment by TinCanTech** [comment]
Closed via https://github.com/OpenVPN/easy-rsa/commit/cb869ee269ac179d67265ceb3ab7569bd04e2c38

**Pull request closed without merging**
