### PR TITLE
doc: Add 'ed' option to EASYRSA_ALGO

### PR DESCRIPTION
**Pull request by mnme**
Related to #488

### CODE REVIEW

**Comment by TinCanTech** [comment]
@mnme Why did you choose to add a new line ?

**Comment by mnme** [comment]
The whole file is formatted with a maximum line length of 80 characters, so I chose to respect that limit.

**Comment by TinCanTech** [comment]
Indeed, you are correct.  The `.md` formatting will append `ed` to the line, where I expected it to be.  However, other wrapped lines include `   ` (3 spaces) indent.

**Review by TinCanTech — APPROVED** [review]

**Comment by mnme** [comment]
Do I need to sign the commit so that you can merge it?

**Comment by TinCanTech** [comment]
For `code` changes I expect signing is required but for this minor documentation change this PR is probably suitable _as-is_.

**Comment by TinCanTech** [comment]
@mnme Because you have reviewed `doc/EasyRSA-Advanced.md`, if you have any other corrections then please add them to this PR for inclusion.

**Comment by TinCanTech** [comment]
@mnme could you please sign this PR.

**Comment by TinCanTech** [comment]
Mege squashed via 2ab720513106710ad543e3a4490b85b1337e949f

**Comment by mnme** [comment]
Sorry for not responding/signing and thank you for merging it!

**Pull request closed without merging**
